/**
 * This is a placeholder for the generated Convex API.
 * The actual file would be generated by Convex based on the schema and functions.
 */

// Mock the Convex function reference structure
// In a real application, these would be generated by Convex
export const api = {
  messages: {
    send: { 
      // These properties mirror what Convex generates
      _type: "mutation",
      _internalName: "messages:send",
    } as any,
  },
  avatarUsage: {
    track: { 
      _type: "mutation",
      _internalName: "avatarUsage:track",
    } as any,
  },
}; 